name: lebenswiki_app
description: The official Lebenswiki App Repository.

publish_to: "none"
version: 1.1.7

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.2.0
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.12
  flutter_riverpod: ^1.0.4
  intl: ^0.17.0
  flutter_speed_dial: ^5.1.0
  expandable_page_view: ^1.0.14
  flutter_secure_storage: ^5.0.2
  another_flushbar: ^1.10.29
  hexcolor: ^2.0.7
  carousel_slider: ^4.1.1
  google_nav_bar: ^5.0.6
  emojis: ^0.9.9
  either_dart: ^0.2.0
  animate_icons: ^2.0.0
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8
  path: ^1.8.1
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.1
  flutter_image_compress: ^1.1.3
  animate_gradient: ^0.0.2
  url_launcher: ^6.1.6
  enum_to_string: ^2.0.1
  flutter_svg: ^1.1.6
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/emojis/
    - assets/images/
    - assets/avatars/

  fonts:
    - family: Lebenswiki
      fonts:
        - asset: assets/fonts/Lebenswiki.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
          weight: 900
