name: lebenswiki_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.2.0
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.12
  flutter_emoji: ^2.4.0
  flutter_riverpod: ^1.0.3
  intl: ^0.17.0
  flutter_email_sender: ^5.1.0
  quill_markdown: ^0.1.0
  flutter_markdown: ^0.6.9+1
  share_plus: ^4.0.4
  hive: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/person_verified.png
    - assets/icons/community.png
    - assets/icons/search.png
    - assets/icons/bookmark.png
    - assets/icons/bookmark_filled.png
    - assets/icons/lebenswiki_icon.png
    - assets/icons/upvote.png
    - assets/icons/downvote.png
    - assets/icons/profile_icon.png
    - assets/icons/share_icon.png
    - assets/emojis/catheart.png
    - assets/emojis/clap.png
    - assets/emojis/happy.png
    - assets/emojis/heart.png
    - assets/emojis/heartsmiley.png
    - assets/emojis/laughing.png
    - assets/emojis/money.png
    - assets/emojis/thinking.png
    - assets/emojis/thumbsup.png
    - assets/emojis/add_reaction.png
    - assets/icons/verified_person_filled.png
    - assets/icons/community_filled.png
    - assets/images/zins_graph.png
    - assets/images/investieren_pack_image.png

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
          weight: 900