name: lebenswiki_app
description: The official Lebenswiki App Repository.

publish_to: "none"
version: 1.4.2+12

environment:
  sdk: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter

  dart_jsonwebtoken: ^3.2.0
  flutter_slidable: ^4.0.0
  file: ^7.0.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  uuid: ^4.3.3
  shared_preferences: ^2.0.12
  flutter_riverpod: ^2.4.10
  # Date Stuff
  intl: ^0.20.2
  flutter_speed_dial: ^7.0.0
  expandable_page_view: ^1.0.14
  flutter_secure_storage: ^10.0.0-beta.4
  another_flushbar: ^1.12.30
  # Convert rgb to hex and reverse
  hexcolor: ^3.0.1
  carousel_slider: ^5.0.0
  google_nav_bar: ^5.0.6
  # For Reactions Functionality, please replace (package too old)
  emojis: ^0.9.9
  either_dart: ^1.0.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  url_launcher: ^6.3.1
  # Need this to show some svg files
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  sensors_plus: ^6.1.1
  device_info_plus: ^11.3.3
  go_router: ^14.8.1
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  image_path: "assets/main_icon/icon.png"
  adaptive_icon_background: "assets/main_icon/background.png"
  adaptive_icon_foreground: "assets/main_icon/light.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/emojis/
    - assets/images/
    - assets/avatars/

  fonts:
    - family: Lebenswiki
      fonts:
        - asset: assets/fonts/Lebenswiki.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
          weight: 900
