name: lebenswiki_app
description: The official Lebenswiki App Repository.
publish_to: "none"
version: 1.5.1+17

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dart_jsonwebtoken: ^3.2.0
  flutter_slidable: ^4.0.3
  file: ^7.0.1
  google_fonts: ^6.3.2
  http: ^1.5.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  flutter_riverpod: ^3.0.2
  intl: ^0.20.2
  flutter_speed_dial: ^7.0.0
  expandable_page_view: ^1.0.17 # OLD
  flutter_secure_storage: ^9.2.4
  another_flushbar: ^1.12.32
  hexcolor: ^3.0.1 # OLD - replace with function
  carousel_slider: ^5.1.1
  google_nav_bar: ^5.0.7
  emojis: ^0.9.9 # OLD - Replace
  either_dart: ^1.0.0 # OLD
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.1
  flutter_dotenv: ^6.0.0
  json_annotation: ^4.9.0
  sensors_plus: ^7.0.0
  device_info_plus: ^12.1.0
  go_router: ^16.2.4
  share_plus: ^12.0.0
  image_picker: ^1.2.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^5.0.0
  # build_runner: ^2.9.0
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: "assets/main_icon/icon.png"
  adaptive_icon_background: "assets/main_icon/background.png"
  adaptive_icon_foreground: "assets/main_icon/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/emojis/
    - assets/images/
    - assets/avatars/

  fonts:
    - family: Lebenswiki
      fonts:
        - asset: assets/fonts/Lebenswiki.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
          weight: 900
